name: 'Miesięczna aktualizacja danych'

on:
  workflow_dispatch:
  schedule:
    # Run montly at 26th
    - cron: '0 0 26 * *'
 

jobs:       
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          netlify-config-path: './netlify.toml'
          production-branch: master
          deploy-message: "Deployed from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
