name: 'Miesięczna aktualizacja danych'

on:
  workflow_dispatch:
  schedule:
    # Run montly at 26th
    - cron: '0 0 26 * *'
 

jobs:       
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          install_command: "cd .. & make install"
          build_command: "cd .. & make deploy"
          NETLIFY_DEPLOY_TO_PROD: true
