name: 'Miesięczna aktualizacja danych'
on:
  workflow_dispatch:
  schedule:
    # Run montly at 26th
    - cron: '0 0 26 * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
