name: 'Ręczna aktualizacja danych'
on:
  workflow_dispatch:
jobs:
  build:
    name: Request deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.DEPLOY_HOOK_URL }}
